<?php $currency = new Zend_Currency(); ?>
<h2>Total</h2>
<table id="summary-totals">
    <thead>
        <tr>
            <th>Starting Balance</th>
            <th>Total Income</th>
            <th>Total Spent</th>
			<th>Total Remaining</th>
			<th>Currently Available</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="number"><?= $currency->setValue($this->totalStarting)?></td>
            <td class="number"><?= $currency->setValue($this->totalIncome)?></td>
            <td class="number"><?= $currency->setValue($this->totalSpent)?></td>
            <td class="number"><?= $currency->setValue($this->totalRemaining)?></td>
            <td class="number"><?= $currency->setValue($this->totalCurrent)?></td>
        </tr>
    </tbody>
</table>
<h2>Expense Summaries</h2>
<table id="expense-summaries">
    <thead>
        <tr>
            <th>Expense</th>
            <th>Starting Balance</th>
            <th>Total Allocated</th>
            <th>Total Spent</th>
            <th>Total Remaining</th>
            <th>Currently Available</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->expenses as $id => $expense) : ?>
        <tr>
            <td><?= $expense->name ?></td>
            <td class="number"><?= $currency->setValue($this->expenseStart[$id])?></td>
            <td class="number"><?= $currency->setValue($this->expenseAllocated[$id])?></td>
            <td class="number"><?= $currency->setValue($this->expenseSpent[$id])?></td>
            <td class="number"><?= $currency->setValue($this->expenseRemaining[$id])?></td>
            <td class="number"><?= $currency->setValue($this->expenseCurrent[$id])?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
