<div id="accordion">
	<h3><a href="#">Recurring Income</a></h3>
	<div>
		<?= $this->button(array(
			'id' => 'new-recurring', 
			'text' => 'New', 
			'ajax' => true,
			'class' => 'right',
			'url' => array('controller' => 'income', 'action' => 'edit-recurring'),
			)); ?>
		<div id="recurring-incomes">
			<?php foreach($this->recurring as $income) : ?>
			<?= $this->partial('partials/recurring-income.phtml', array('income' => $income)) ?>
			<?php endforeach; ?>
		</div>
		<div class="clearfix"></div>
	</div>
	<h3><a href="#">Expense Categories</a></h3>
	<div>
		<?= $this->button(array(
			'id' => 'new-category', 
			'text' => 'New', 
			'ajax' => true,
			'class' => 'right',
			'url' => array('controller' => 'expense', 'action' => 'edit-category'),
			)); ?>	
		<div id="expense-categories">
			<?= $this->partial('partials/category-list.phtml', array('categories' => $this->categories)) ?>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	wireSettings();
});
</script>