<?php echo $this->doctype(), PHP_EOL; ?>
<html> 
<head>  
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
	<title>Finance Director</title>
<?php
$this->headScript()->appendFile("/fixedheadertable/jquery.fixedheadertable.1.1.2.js");
$this->headScript()->appendFile('/js/jquery.jeditable.js');
$this->headScript()->appendFile('/js/jquery.jeditable.datepicker.js');
$this->headScript()->appendFile('/js/jquery.cookie.js');

$this->headScript()->appendFile('/uploadify/swfobject.js');

if(APPLICATION_ENV == 'production')
{
	$this->headScript()->appendFile('/uploadify/jquery.uploadify.v2.1.0.min.js');
	$this->headScript()->prependFile("/gritter/js/jquery.gritter.min.js");
	$this->headScript()->prependFile("/jquery/js/jquery-ui-1.8.4.custom.min.js");
	$this->headScript()->prependFile("/jquery/js/jquery-1.4.2.min.js");
}
else
{
	$this->headScript()->appendFile('/uploadify/jquery.uploadify.v2.1.0.js');
	$this->headScript()->prependFile("/gritter/js/jquery.gritter.js");
	$this->headScript()->prependFile("/jquery/development-bundle/ui/jquery-ui-1.8.4.custom.js");
	$this->headScript()->prependFile("/jquery/development-bundle/jquery-1.4.2.js");
}

$time = filemtime(APPLICATION_PATH . '/../public/js/finance.js');
$this->headScript()->appendFile("/js/finance.{$time}.js");

$this->headLink()->appendStylesheet('/css/yui-3.1.2-fonts-reset-base.css');
$this->headLink()->appendStylesheet('/jquery/css/cupertino/jquery-ui-1.8.4.custom.css');
$this->headLink()->appendStylesheet('/gritter/css/jquery.gritter.css');
$this->headLink()->appendStylesheet('/uploadify/uploadify.css');

$time = filemtime(APPLICATION_PATH . '/../public/css/finance.css');
$this->headLink()->appendStylesheet("/css/finance.{$time}.css");

echo $this->headLink(), PHP_EOL;
echo $this->headScript(), PHP_EOL;
?>
</head> 
<body>
	<div id="wrapper"> 
		<div id="header">
			<?php if(Zend_Auth::getInstance()->hasIdentity()) : ?>
			<div id="controls">
				<?= $this->partial('partials/user.phtml') ?>
				<?= $this->partial('partials/date-selector.phtml')  ?>
			</div>
			<?php endif; ?>
			<h1>Finance Director</h1>
		</div> 
		<div id="content">
			<?= $this->layout()->content ?>
		</div> 
		<div id="footer">
			<p>&copy; Copyright <?=strftime("%G")?> Finance Director. All rights reserved.</p>
		</div> 
	</div>
</body>
</html>
