<div id="transaction-forms">
	<div class="transaction-form ui-widget-content ui-corner-all">
		<h3>New Transaction</h3>
		<?= $this->form ?>
		<div class="buttons">
			<?= $this->button(array(
				'id' => 'new-transaction', 
				'text' => 'Save',
				'class' => 'right', 
				'url' => array('controller' => 'transaction', 'action' => 'edit'),
				)); ?>
			<div class="clearfix"></div>
		</div>
	</div>
	<div class="transaction-form ui-widget-content ui-corner-all">
		<h3>Import Transactions</h3>
		<ol class="help">
			<li>Download transactions in the OFX or Microsoft Money format</li>
			<li>Click Browse and upload that file</li>
		</ol>
		<?php if(isset($this->lastImport)) : ?>
			<p>Last Import: <?= $this->lastImport->displayDate() ?></p>
		<?php endif; ?>
		<input id="upload-input" name="transactions" type="file" />
	</div>
</div>
<div id="transaction-table">
	<table>
		<thead>
			<tr>
				<th>Date</th>
				<th>Check</th>
				<th>Description</th>
				<th>Amount</th>
				<th>Expense</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<?php $row = 0; ?>
			<?php foreach($this->transactions as $transaction) : ?>
			<?php $rowClass = ($row++ % 2 == 0) ? 'even' : 'odd'; ?>
			<tr class="transaction <?= $rowClass ?>" data-transaction="<?= $transaction->id  ?>">
				<td class="date"><?= $transaction->displayDate() ?></td>
				<td class="check_num">
				<?php if($transaction->check_num > 0) : ?>
					<?= $transaction->check_num ?>
				<?php else: ?>
					&nbsp;
				<?php endif; ?>
				</td>
				<td class="description"><?= $transaction->description ?></td>
				<td class="amount"><?= $transaction->displayCurrency() ?></td>
				<td class="expense"><?= $this->expenses[$transaction->expense_id]->name ?></td>
				<td>
					<?= $this->button(array(
						'text' => 'Delete',
						'class' => 'delete', 
						'url' => array('controller' => 'transaction', 'action' => 'delete', 'transaction_id' => $transaction->id),
						)); ?>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<?= $this->paginator ?>
</div>
<div class="clearfix"></div>
<script type="text/javascript">
$(document).ready(function(){
	wireTransactions({
		doImport: <?= json_encode($this->import) ?>,
		scriptData: {
			<?= session_name() ?>: '<?= session_id() ?>'
		},
		expenseOptions: <?= json_encode($this->expenseOptions, JSON_FORCE_OBJECT) ?>
	});
});
</script>