<div id="recurring-income-<?= $this->income->id ?>" class="recurring-income ui-corner-tr">
	<?= $this->button(array(
		'class' => 'edit-recurring right', 
		'text' => 'Edit',
		'ajax' => true,
		'url' => array('controller' => 'income', 'action' => 'edit-recurring', 'recurring_income_id' => $this->income->id),
		)); ?>
	<div class="name"><?= $this->income->name ?></div>
	<div class="amount"><?= $this->income->displayCurrency() ?></div>
	<div class="recurrance"><?= $this->income->displayRecurType() ?></div>
	<div class="start-date"><span class="label">Start:</span> <?= $this->income->displayDate('start_date') ?></div>
	<?php if($this->income->end_date > 0) : ?>
	<div class="end-date"><span class="label">End:</span> <?= $this->income->displayDate('end_date') ?></div>
	<?php endif; ?>
</div>